### ISSUE TITLE
wine compatible... or mac version...

### ISSUE THREAD

**Issue by yasars** [StudentBlake/XCI-Explorer#11]
hello thank you for this nice project... after 1.30 your program is no longer wine compatible can you fix that or can you make/build an mac version ??

thank you !!!

// XCI-Organizer is wine compatible and is working 👍

**Comment by StudentBlake** [comment]
XCI Organizer and Explorer almost use the same code base so I’m not sure why one works and the other one doesn’t. That said, this is a Windows only release, sorry.
