### ISSUE TITLE
nstoolmod.exe crashes on windows 7

### ISSUE THREAD

**Issue by PeterMaxu** [StudentBlake/XCI-Explorer#12]
nstoolmod.exe crashes on windows 7
newest c++ redistr. are installed

**Comment by ceedveed** [comment]
Same here on Windows 7

**Comment by StudentBlake** [comment]
Will you guys test the latest version of nstoolmod and see if it works?
[nstoolmod.zip](https://github.com/StudentBlake/XCI-Explorer/files/2279018/nstoolmod.zip)

**Comment by ceedveed** [comment]
I tried the nstoolmod attachment, and it still crashes on Windows 7.

**Comment by Dreamcast2** [comment]
@StudentBlake Still crash，.net also reported wrong，my friends are the same situation on Win7.
Load .xci is ok，only .nsp crash.
Windows 7 SP1 x64 Ultimate Simplified Chinese，.NET 4.7.2，VC++ 2005~2017 All.

**Comment by buggii** [comment]
Same problem here with .nsp under Win7. Can you provide a compiled 1.3 version to temporarily solve the problem ?

**Comment by StudentBlake** [comment]
Please try the latest version here: https://github.com/StudentBlake/XCI-Explorer/releases/download/v1.4.1/XCI-Explorer-v1.4.1.zip

**Comment by buggii** [comment]
It works now on Win7 ! THANK YOU ! 
Is it an issue that "Partitions" tab is empty opening .nsp files ? Is it possible to add .nsp extraction providing the correct key ?

**Comment by Dreamcast2** [comment]
@StudentBlake v1.4.1 works now on Win7，thank you so much.

**Comment by StudentBlake** [comment]
@buggii Partitions tab isn't supported yet for NSP. Maybe soon.

**Comment by ceedveed** [comment]
Works on Windows 7 now. Thank you! Scrape is not slow on NSPs too.
