### ISSUE TITLE
1.4.0 does not show game name, images, revision, etc.

### ISSUE THREAD

**Issue by mbaxjxb2** [StudentBlake/XCI-Explorer#13]
As shown in the picture below, some information is missing after upgrading to 1.4.0.
![image](https://user-images.githubusercontent.com/42386065/44105696-08f007aa-a025-11e8-8a56-a2cb102afcf8.png)
Revert to 1.2.4 everything is just fine.
![image](https://user-images.githubusercontent.com/42386065/44105866-96930882-a025-11e8-857c-310e5fc89d6a.png)

**Comment by alisaeed02** [comment]
it happens to me also but just on "The Legend of Zelda"

**Comment by StudentBlake** [comment]
Interesting as I can't reproduce it. What does the root directory look like for XCI Explorer 1.4?

**Comment by StudentBlake** [comment]
Looks like the new version of hactool broke something. Thanks for letting me know.
