### ISSUE TITLE
Super Bombermen R Rev.001 cannot be opened

### ISSUE THREAD

**Issue by buggii** [StudentBlake/XCI-Explorer#17]
Opening Super Bombermen R Rev.001 XCI gives an error and crashes the program. The game seems to work fine in SX OS.

**Comment by garoxas** [comment]
afaik this issue has been here since forever. have no idea why it can survive this long without anyone noticing (and with no other games complaining)

it's this part
https://github.com/garoxas/XCI-Explorer/commit/de7e2878b12ffd158eb6c9137a3c9f0196974da5#diff-e21268273aca59e8b3f9b19ed21cedb2L866

**Comment by garoxas** [comment]
yes

![bomb](https://user-images.githubusercontent.com/11901820/45101593-0a206880-b156-11e8-9783-3699984a1053.png)
