### ISSUE TITLE
Latest XCI Explorer Crashes When Opening Some Updates

### ISSUE THREAD

**Issue by mancupo** [StudentBlake/XCI-Explorer#19]
Aces of the Luftwaffe Squadron [UPD][0100b28003440800][v131072].nsp
Gear Club Unlimited [UPD][010065e003fd8800][v131072].nsp
Hollow Knight [UPD][0100633007d48800][v131072].nsp
L.A. Noire [UPD][0100830004fb6800][v131072].nsp
Rime [UPD][0100a62002042800][v131072].nsp
Rocket League [UPD][01005ee0036ec800][v655360].nsp
South Park The Fractured But Whole [UPD][01008f2005154800][v327680].nsp
The Pinball Arcade [UPD][0100cd300880e800][v196608].nsp

Verified OK by Switch Backup Manager v1.1.5

**Comment by 18Phoenix** [comment]
With these 3 updates I've a problem, too.
The XCI-Explorer shows only the size, nothing else. No title ID, no name, no icon, nothing.

Hollow Knight [UPD][0100633007d48800][v131072].nsp
South Park The Fractured But Whole [UPD][01008f2005154800][v327680].nsp
The Pinball Arcade [UPD][0100cd300880e800][v196608].nsp

**Comment by StudentBlake** [comment]
Are you using the latest v1.4.2 the was recently released?

**Comment by 18Phoenix** [comment]
Yep.

**Comment by StudentBlake** [comment]
I think I found the issue. Try this one out and let me know if it breaks anything!
[XCI-Explorer.zip](https://github.com/StudentBlake/XCI-Explorer/files/2349383/XCI-Explorer.zip)

**Comment by 18Phoenix** [comment]
Cool, this one works, thanks ^^

**Comment by 18Phoenix** [comment]
Often, I copy the title ID from the Explorer and want to insert it in the nsp-file-name.
But I can't because it's locked by the program.
Couldn't the file set free after reading out ?
Would be great :D

**Comment by StudentBlake** [comment]
Yea I noticed this a while back, but haven’t figured what’s keeping the file locked. I’ll have to investigate further.
