### ISSUE TITLE
MasterKey5 not working correct

### ISSUE THREAD

**Issue by 20Phoenix** [StudentBlake/XCI-Explorer#31]
Hello :)
There seem to be problems with MasterKey5 (6.0.0-6.1.0) files.
Title ID and MasterKey are shown, but no game revision, no icon, no name.

![grafik](https://user-images.githubusercontent.com/31387801/49114590-d9555880-f298-11e8-816e-bcb0bcb0eda9.png)

**Comment by StudentBlake** [comment]
Bad NSP? Looks like the size is off by 1 byte.
![image](https://user-images.githubusercontent.com/6874208/49117843-253fd780-f270-11e8-88cb-277e6891d749.png)

**Comment by 20Phoenix** [comment]
I checked it with over 10 NSP, always the same.
Can't believe that they're all bad. In SX OS the icons are shown correct.

**Comment by 20Phoenix** [comment]
I just deleted the prog and reinstalled it. Suddenly it works, even with 1 byte less ;)
Very strage.

![grafik](https://user-images.githubusercontent.com/31387801/49136799-09c5e280-f2eb-11e8-815b-bff1256fa40f.png)

**Comment by 20Phoenix** [comment]
Do you know a new Get-keys.bat to get keys including the new level 5 values ?
