### ISSUE TITLE
NSP files patched with NSC_Builder_v0.75.b don't show any infos

### ISSUE THREAD

**Issue by 20Phoenix** [StudentBlake/XCI-Explorer#33]
Ok, the unpatched files work with the XCI Explorer, the patched ones don't.
But the patched files are ok and they work with SX OS.
For the explorer I use the newest keys including MasterKey6.

**Comment by StudentBlake** [comment]
Download this and extract it somewhere: https://github.com/jakcron/NNTools/releases
Run the command `nstool.exe --listfs [DRAG NSP HERE]`
Post picture of output.

**Comment by 20Phoenix** [comment]
![grafik](https://user-images.githubusercontent.com/31387801/49790102-b5305780-fd2d-11e8-8c5d-a767f01c7890.png)

OK, I see the problem: xml is missing, correct ?

**Comment by 20Phoenix** [comment]
But the infos are somewhere else included, even without xml.

**Comment by StudentBlake** [comment]
Yes, that’s true. The current implementation relies on the XML, but it should be possible to rewrite.

**Comment by 20Phoenix** [comment]
I don't think so.
The tool NSC Builder (https://github.com/julesontheroad/NSC_BUILDER) gives all these infos even without XML.

**Comment by garoxas** [comment]
my bad, apparently minimum required fw is also available in cnmt.nca
https://switchbrew.org/wiki/NCA#Application_header

**Comment by StudentBlake** [comment]
Fixed in latest v1.4.8
