### ISSUE TITLE
Hope to support WIN10

### ISSUE THREAD

**Issue by Aeuko** [StudentBlake/XCI-Explorer#38]
Win10 will show incomplete, only the capacity and title, Win7 is no problem.

**Comment by StudentBlake** [comment]
What version of WIndows 10 are you using? I personally build it on Windows 10.

**Comment by Aeuko** [comment]
WIN10 1809  Professional version x64

I have been bothering me for a long time, I have failed in many win10 tests, currently I can only use win7 to view

**Comment by StudentBlake** [comment]
Is it the English version or multi-language?

**Comment by Aeuko** [comment]
multi-language，I am using Chinese

**Comment by StudentBlake** [comment]
I think it's a bug in hactool. Try this version and extract it to tools https://github.com/SciresM/hactool/releases/download/1.2.0/hactool-1.2.0.win.zip

**Comment by Aeuko** [comment]
Tested, still not showing

**Comment by 20Phoenix** [comment]
I never had problems with Win10.
