### ISSUE TITLE
Master Key 07/08 support

### ISSUE THREAD

**Issue by Buzbee** [StudentBlake/XCI-Explorer#39]
After manually adding master_key_07 to the generated keys.txt file, Yoshi's Crafted World (original NSP from eShop) only shows size and that it is eShop with 1.4.6. The 1.01 update fills in all blanks and shows "MasterKey7 (?)" for MasterKey Revision. Must be a bug with MasterKey detection as the XCI version is MasterKey 4 for the original game.

**Comment by StudentBlake** [comment]
The latest version (v1.4.7) should show proper info for MasterKey 7.
