### ISSUE TITLE
Doesn't find icon dat for some supported languages

### ISSUE THREAD

**Issue by StudentBlake** [StudentBlake/XCI-Explorer#4]
Look at line 285 in MainForm.cs. I'm mainly experiencing this with 1-2 Switch. Take out the try-catch and see for yourself. The information might be located somewhere else.

**Comment by klks** [comment]
i looked into the packages, the icons are not there, so for 1-2 switch it is correct, i've pushed a fix to show the languages it supports but show blank icons for those that dont have it.
