### ISSUE TITLE
No infos for one of the newer games.

### ISSUE THREAD

**Issue by 20Phoenix** [StudentBlake/XCI-Explorer#41]
Hello.
I made a new SuperXCI for **Overcooked 2** including the newest update 1.0.9 and all 4 DLCs.
It works fine on Switch.
But the XCI-Explorer (with the newest keys) shows nothing.
Checking the XCI with NSCB shows that all files are correct and proper.

**Comment by StudentBlake** [comment]
Hi, just checking if you built from source. I need to actually update the release.

**Comment by 20Phoenix** [comment]
I use the normal v1.4.7.

**Comment by StudentBlake** [comment]
Fixed in latest v1.4.8
