### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by bitpit** [StudentBlake/XCI-Explorer#44]
hullo, I wanted to make a sha hash checker for NCAs and it looked like your project might provide me a good head start, and now that .net is cross platform (or so I hear, I haven't been in a windows shop for a while) I could target both platforms. 

however it doesn't look as though you've included a license, so I am unsure whether I would be within my rights to make this a publicly available project, and I'm now realizing that I can't use it privately because what hashes would I verify against.

anyway thanks for looking at this and clarifying, whatever direction you choose.

**Comment by StudentBlake** [comment]
Yes, that's fine. This project is all for learning and improving, and most of it wasn't even my work but work from others! Open source is great :)
