### ISSUE TITLE
Please add support for the .nsz releases

### ISSUE THREAD

**Issue by mancupo** [StudentBlake/XCI-Explorer#45]
Renaming .nsp to .nsz works, so it's just the extension that needs to be recognized by your app.

**Comment by StudentBlake** [comment]
Hi, this is easy to do. Will you test the attached file to see if it works in all cases? I changed around some logic.
[XCI-Explorer-v1.4.8.1-NOT-FINAL.zip](https://github.com/StudentBlake/XCI-Explorer/files/3773773/XCI-Explorer-v1.4.8.1-NOT-FINAL.zip)

**Comment by mancupo** [comment]
Looks good, thank you.

May I make another request or two.
In the Game Revision box, you used to have the version nos reversed (XCI-Explorer-v1.4.4 and below).  Can you give us the option of choosing between the old format "v65536 (1.0.1)" and the newer one "1.0.1 (v65536)".  Personally, I use the old format to rename my update nsp's for Doge's app.

Lastly, is it possible to add a new box that gives us the Required FW for the game/update.  Presently, I have to use Switch Backup Manager to get it.  That would make your app very complete.

Thanks again

**Comment by StudentBlake** [comment]
I have updated for NSZ and changed game revision to display as old format in next build. Thanks!
