### ISSUE TITLE
Unable to find HexBox DLL while building

### ISSUE THREAD

**Issue by CodingKoopa** [StudentBlake/XCI-Explorer#47]
When building XCI Explorer on Windows 10 with Visual Studio Community 2019 and a `Release` configuration, I get these messages:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1566	Error reading resource 'XCI_Explorer.Be.Windows.Forms.HexBox.dll' -- 'Could not find file 'C:\Users\Kyle\Documents\Projects\C#\XCI-Explorer-master\Be.Windows.Forms.HexBox.dll'.'	XCI Explorer	C:\Users\Kyle\Documents\Projects\C#\XCI-Explorer-master\CSC	1	Active
Warning		The referenced component 'Be.Windows.Forms.HexBox' could not be found.	XCI Explorer			
```
I'm not familiar with C#'s package management, but I noticed that this DLL is provided by the [`Be.Windows.Forms.HexBox` NuGet package](https://www.nuget.org/packages/Be.Windows.Forms.HexBox/), which is referenced by the [`packages.conf`](https://github.com/StudentBlake/XCI-Explorer/blob/8965a7376b6524125138603ddbb0d8f32153e228/packages.config#L3). For me, I was able to mitigate the error by changing [this](https://github.com/StudentBlake/XCI-Explorer/blob/8965a7376b6524125138603ddbb0d8f32153e228/XCI%20Explorer.csproj#L92) line of the `CSProj` file to:
```xml
    <EmbeddedResource Include="packages\Be.Windows.Forms.HexBox.1.6.1\lib\net40\Be.Windows.Forms.HexBox.dll" />
```
This allowed the program to build for me. However, I have not submitted this as a pull request because I'm not sure if this is a configuration error on my end and it's supposed to be able to find the DLL from the current reference.

**Comment by garoxas** [comment]
actually just remove Be.Windows.Forms.HexBox.dll from solution explorer will suffice

or if you want to edit csproj directly, you can use this diff below (basically delete line 91 to 93)
```
diff --git a/XCI Explorer.csproj b/XCI Explorer.csproj
index 70c8fbe..5dfa912 100644
--- a/XCI Explorer.csproj
+++ b/XCI Explorer.csproj
@@ -88,8 +88,5 @@
     <None Include="app.config" />
     <None Include="packages.config" />
   </ItemGroup>
-  <ItemGroup>
-    <EmbeddedResource Include="Be.Windows.Forms.HexBox.dll" />
-  </ItemGroup>
   <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
 </Project>
```

**Comment by CodingKoopa** [comment]
Removing `Be.Windows.Forms.HexBox.dll` from the solution explorer did resolve the problem for me. I'm gonna leave this issue open, as I'm not sure if you plan on amending the readme or making the resource optional. Cheers :)

**Comment by StudentBlake** [comment]
Hi, I simply added it the ignore list in hopes people wouldn't blindly trust my precompiled DLL. I realize this is a tiny bit of a hassle, so I've added it back in.
