### ISSUE TITLE
Game Revision not always up to date

### ISSUE THREAD

**Issue by StudentBlake** [StudentBlake/XCI-Explorer#5]
From a conversation I had with someone:
`On to of that, if the game has an update built into it, like the revised games, you'll even have more than one control NCA
You'd need another method to find out which one was the original and which is for the update so you get the proper revision number`
Some games have 150+ NCAs in the update partition.

**Comment by klks** [comment]
do you know a game like this i can look at?

**Comment by StudentBlake** [comment]
For example, the new revision of BOTW will show 1.0.0.

**Comment by EclipseSin** [comment]
BOTW carts containing an updated version of the game are actually of version 1.0.0. They include the update in a separate NCA along with it's version information.

Likely this is reading cart information and the switch reads the update directly. I don't know about Rev001, but I own Rev002. When extracted, it is the base game, and an update including it's tik and cert. 

Maybe can be turned into an NSP, but that's a topic for another day.

**Comment by StudentBlake** [comment]
I'm pretty sure it's possible to get the proper revision, but I'm not an expert when it comes to this stuff. Whether it's worth the work to get the latest NCA info from the cart is another story.

**Comment by garoxas** [comment]
yes it is possible to do that
I'll see if I can implement the changes I just made to GibaBR's Switch Backup Manager here

![sbm](https://user-images.githubusercontent.com/11901820/44226439-519c8000-a1ba-11e8-8df4-d71d5b56534c.PNG)

but if you want to do this yourself, feel free to check my findings here https://github.com/gibaBR/Switch-Backup-Manager/issues/37

**Comment by garoxas** [comment]
#15 
that was fast 😄 
you sharing lots of code with GibaBR sure helps a lot

![xci](https://user-images.githubusercontent.com/11901820/44228942-c96da900-a1c0-11e8-9ab8-801f612f1449.PNG)

**Comment by StudentBlake** [comment]
Thanks for your work!
