### ISSUE TITLE
New Version With Detailed Game Contents 

### ISSUE THREAD

**Issue by zzpong** [StudentBlake/XCI-Explorer#54]
There are quite amout of packaged xci or nsp files which contain both base game, updates and even DLCs. Hence I made some changes of the original XCI-Explorer interface, which can be seen below.
![example](https://user-images.githubusercontent.com/8416883/78872143-60b0ff80-7a7b-11ea-8487-2ac0cdcc6bf8.png)

Beside this main change, I also add some features, like:
- support nsp file extraction;
- fix a problem that small file extraction failed to work properly.

But I don't konw if you would like this modification, so if you want me to submit a PR, just let me know.

**Comment by StudentBlake** [comment]
I think these are all great changes. Feel free to submit a PR.

Thanks for taking time to work on this!

**Comment by zzpong** [comment]
You are welcome. XCI-Explorer maintained under your supervision really helps me a lot, so I'm glad to help~
