### ISSUE TITLE
Please add the latest MasterKeys

### ISSUE THREAD

**Issue by mancupo** [StudentBlake/XCI-Explorer#61]
Some game updates are using the latest masterkey (_b or _c)
What XCI-Explorer shows instead is MasterKey 0, but the base game clearly shows 10, so 0 cannot be true.
One example of this is Mario Party Superstars.
![MPS_base](https://user-images.githubusercontent.com/36773826/139557684-20cc4c94-31b4-403c-9534-c1743808d2c9.jpg)
![MPS_update](https://user-images.githubusercontent.com/36773826/139557690-ae233b6f-92dd-4f57-ba20-7ec29627ca78.jpg)

**Comment by StudentBlake** [comment]
Hello, I see the issue. 

Side note, what OS are you on by the way? I'm probably going to update to .NET 6 with a minimum of Windows 7.

**Comment by mancupo** [comment]
I'm using Windows 10 and 7 (dual boot), but I prefer 10 as default

Please see my comment on your first 1.6.0 attempt, as I went back to 1.5.0 for now (it's more convenient for me)
Thanx for all your work
