### ISSUE TITLE
XCI-Explorer 1.6.0 No longer launches when .nsp, .nsz, etc files are opened

### ISSUE THREAD

**Issue by mancupo** [StudentBlake/XCI-Explorer#62]
v1.5.0 would launch and show contents when opening these files in File Explorer (by clicking on them or using Open With)

v1.6.0 only allows one to view contents by doing Load Game (very tedious process)
Thank you very much

**Comment by StudentBlake** [comment]
If you feel like testing this, let me know what you think and if you have any new issues. This include #55 too.
[net6.0-windows-test-2.0.0.zip](https://github.com/StudentBlake/XCI-Explorer/files/7449255/net6.0-windows-test-2.0.0.zip)

**Comment by mancupo** [comment]
net6.0-windows-test-2.0.0 worked nicely (I clicked on my nsp and it launched your app with the rom info in it).
Your keys.txt is missing master_key_0c = xxxxxxxxxxxxxxxxxxxx...
Also, I had to copy hactool.exe myself to the Tools folder (I used the one that came with v1.6.0)

Your v2 can identify any base, upd or dlc that is contained inside an .xci - simply amazing (I've included a good example)

However, this part "GENERAL: 1.6.1 (v12)" should be removed at the top but included for each update (because each upd may have a diff value).  Please do it the way it was on v1.5.0, like so:

[0100225000FEE800][v589824 (1.6.1)]
[01005AA00D676800][v786432 (1.6.1)]

and the (v12) part isn't useful, so it can be removed

![1-top](https://user-images.githubusercontent.com/36773826/139615101-fcb8e557-03be-4034-abab-0cb687db7121.jpg)
![2-middle](https://user-images.githubusercontent.com/36773826/139615135-2bf65b82-20ff-44d8-bb6a-704cfb4439e7.jpg)
![3-bottom](https://user-images.githubusercontent.com/36773826/139615142-1a5a9bef-0804-43e2-9b21-7d5b53752584.jpg)

Thank you very much for this wonderful app.  I use it every day.
