### ISSUE TITLE
[Minor] "Not Responding" while extracting file

### ISSUE THREAD

**Issue by EclipseSin** [StudentBlake/XCI-Explorer#8]
While extracting a file, the program becomes unresponsive and no status is given besides HDD activity and manually checking filesize. 

It would be nice to have the program remain responsive and add a status bar along the bottom for progress.

This is something minor, the program works fine otherwise.

![capture](https://user-images.githubusercontent.com/4019608/42126292-df8e1270-7c53-11e8-875e-53da76236a35.PNG)

**Comment by EclipseSin** [comment]
Seems to be working fine. I did notice the CERT buttons are not locked during extraction. May be a good idea to lock at least import and clear. 

I tried using clear for the heck of it while extracting a NCA file and received a .NET error (kind of expected some error). Works fine again after extraction is complete.

Extracted NCA into expected files. Will let you know if I see anything.

**Comment by StudentBlake** [comment]
Good point. Thanks
