### ISSUE TITLE
Modified MainForm to allow Double Click of an XCI file to work - Very small changes

### ISSUE THREAD

**Issue by madusmacus** [StudentBlake/XCI-Explorer#9]
public MainForm()
    {

      InitializeComponent();
      string assemblyVersion = Assembly.GetExecutingAssembly().GetName().Version.ToString();
      this.Text = "XCI Explorer v" + assemblyVersion;
      LB_SelectedData.Text = "";
      LB_DataOffset.Text = "";
      LB_DataSize.Text = "";
      LB_HashedRegionSize.Text = "";
      LB_ActualHash.Text = "";
      LB_ExpectedHash.Text = "";

      //MAC - Set Current Directory to application directory so it can find the keys
      String startupPath = Application.StartupPath;
      Directory.SetCurrentDirectory(startupPath);
      //MAC - End

      if (!File.Exists("keys.txt"))
      {
        if (File.Exists("Get-keys.txt.bat") && MessageBox.Show("keys.txt is missing.\nDo you want to automatically download it now?", "XCI Explorer", MessageBoxButtons.YesNo) == DialogResult.Yes)
        {
          Process process = new Process();
          process.StartInfo = new ProcessStartInfo
          {
            WindowStyle = ProcessWindowStyle.Hidden,
            FileName = "Get-keys.txt.bat"
          };
          process.Start();
          process.WaitForExit();
        }

        if (!File.Exists("keys.txt"))
        {
          MessageBox.Show("keys.txt failed to load.\nPlease include keys.txt in this location.");
          Environment.Exit(0);
        }
      }
      if (!File.Exists("hactool.exe"))
      {
        MessageBox.Show("hactool.exe is missing.");
        Environment.Exit(0);
      }
      getKey();
     
      //MAC - Set the double clicked file name into the UI and process file
      String[] args = Environment.GetCommandLineArgs();
      if (args.Length > 1)
      {
        TB_File.Text = args[1];
        Application.DoEvents();
        ProcessFile();
      }
      //MAC - End

    }

**Comment by StudentBlake** [comment]
Thanks, this is great. I added into next build.
